#import "./AnswerFragment.gql"

subscription questionUpdated ($sessionId: ID!, $filter: QuestionsFilter!) {
  questionUpdated (sessionId: $sessionId, filter: $filter) {
    id
    title
    content
    votes
    answered
    answerCount
    pickedAnswer {
      ...Answer
    }
  }
}
