fragment Session on Session {
  id
  title
  public
  user {
    id
    avatar
    name
  }
  date
}

fragment SessionDetails on Session {
  id
  description
  questionCount
}

fragment SessionAsAdmin on Session {
  id
  user {
    email
  }
}
